# Store app config (the public app we submit to the Shopify App Store).
# Use with: shopify app deploy --config singles

client_id = "1fef72d2b05300b517964b5676b93892"
name = "Singles Magic: The Gathering"
application_url = "https://app-singles.arkanexus.cl"
embedded = true
handle = "singles-magic-the-gathering"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/subscriptions_update"
  topics = [ "app_subscriptions/update" ]

[access_scopes]
scopes = "read_products,write_products,write_inventory"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://app-singles.arkanexus.cl/auth/callback" ]
